version: '3'

services:
  web:
    image: ${DOCKER_REPO}web-${BUILD_NUMBER}-${BUILD_DATE}
    ports:
      - "7070:80"
    depends_on:
      - database
    volumes:
      - ./uploaded_img:/var/www/html/uploaded_img
    environment:
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: shop
      MYSQL_USER: root
      MYSQL_PASSWORD: ""

  database:
    image: ${DOCKER_REPO}db-${BUILD_NUMBER}-${BUILD_DATE}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: shop
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./shop_db.sql:/docker-entrypoint-initdb.d/shop_db.sql

  phpmyadmin:
    image: ${DOCKER_REPO}phpmyadmin-${BUILD_NUMBER}-${BUILD_DATE}
    ports:
      - "9090:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: ""

